Import("env")

smpl_env = env.Clone(LIBS=["pthread", "upp"])
async_smpl = smpl_env.Program("async", ["async.cpp"])
cli_smpl = smpl_env.Program("cliparser", ["cliparser.cpp"])
samples = smpl_env.Alias("samples", [async_smpl, cli_smpl])
smpl_env.AlwaysBuild(samples)
Help("    samples           Build samples.")
