name: CI
on:
  push:
    branches: [maister]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@v1.6.3
        with:
          packages: meson ninja-build g++-16 libgtest-dev libgmock-dev libboost-all-dev pkgconf libavcodec-dev libavformat-dev
          version: "0.1"
      - name: Build
        env:
          CXX: g++-16
          CC: gcc-16
        run: make
      - name: Test
        run: |
          make test
          make test-smoke
      - name: Lint
        run: |
          make lint
          make format-check
          make format-check-meson
